from typing import Protocol

from kb_core.models import Chunk, Document


class DocumentStore(Protocol):
    def create_document(self, doc: Document) -> Document: ...

    def get_document(self, document_id: str) -> Document | None: ...

    def list_documents(self, collection_id: str, limit: int, offset: int) -> list[Document]: ...

    def update_document(self, doc: Document) -> Document: ...

    def delete_document(self, document_id: str) -> None: ...


class ChunkStore(Protocol):
    def upsert_chunks(self, chunks: list[Chunk]) -> None: ...

    def get_chunks(self, chunk_ids: list[str]) -> list[Chunk]: ...

    def list_chunks_by_document(self, document_id: str, limit: int, offset: int) -> list[Chunk]: ...

    def delete_chunks_by_document(self, document_id: str) -> None: ...
